import { GameStatus } from "../enums/game-status.enum";
import { AwardCategory } from "./awardCategory.model";
import { Character } from "./character.model";
import { Company } from "./company.model";
import { Franchise } from "./franchise.model";
import { Game_Character } from "./game_character.model";
import { Game_Company } from "./game_company.model";
import { Genre } from "./genre.model";
import { Person } from "./person.model";
import { Platform } from "./platform.model";
import { Serie } from "./serie.model";
import { Theme } from "./theme.model";

export interface Game {
    id?: number;
    name: string;
    main_img?: string;
    logo?: string;
    back_cover?: string;
    release_date?: Date;
    score: number;
    format: string;
    price: number;
    num_players?: string;
    alt_name?: string;
    wikipedia?: string;
    color?: string;
    owned?: boolean;
    personal_status?: GameStatus;
    franchiseId?: number;
    serieId?: number;
    franchise?: Franchise;
    serie?: Serie;
    parent_game?: Game;
    genres?: Genre[];
    themes?: Theme[];
    directors?: Person[];
    platforms?: Platform[];
    companies?: Company[];
    characters?: Character[];
    Game_Company?: Game_Company;
    Game_Character?: Game_Character;
    awards?: AwardCategory[];
};
